name: Publish CD

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

            - name: Install stable toolchain 💿
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true

            - name: Publish to crate 🎉
              run: cargo publish --token ${CRATES_TOKEN}
              env:
                  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
