name: Test CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        name: Rust Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - uses: actions-rs/cargo@v1
              with:
                  command: test
